name: Build APK with Dockerized Buildozer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildozer container and build APK
      run: |
        docker run --rm -v ${{ github.workspace }}:/app \
          cdrx/buildozer:latest \
          bash -c "cd /app && buildozer android debug"

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: ritualistism-app
        path: bin/*.apk
