name: Build APK (Docker + Buildozer)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo usermod -aG docker $USER
        docker --version

    - name: Build APK with Buildozer (Docker)
      run: |
        docker run --rm -v ${{ github.workspace }}:/app \
          cdrx/buildozer \
          buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: RitualistismApp-debug
        path: bin/*.apk
